(* ::Package:: *)

(* ::Input:: *)
(*BeginPackage["BattleshipBaseConversion`"];*)
(**)
(**)
(*generateNotebook::usage="generateNotebook[] crea e apre il notebook interattivo.";*)
(**)
(*validateCoordinate::usage="validateCoordinate[coord_Integer, occupied_List] verifica coordinate.";*)
(**)
(*placeShip::usage="placeShip[start_, direction_, size_, occupied_] restituisce coordinate nave.";*)
(**)
(*generateGrid::usage="generateGrid[ships_List] restituisce griglia 10\[Times]10.";*)
(**)
(*createTutorialNotebook::usage="createTutorialNotebook[] crea un notebook con tutorial e spiegazione della conversione di base.";*)
(**)
(*Begin["`Private`"];*)
(**)
(**)
(*ClearAll[validateCoordinate,placeShip,generateGrid,generateNotebook,BoardDisplay,convertInput,createTutorialNotebook];*)
(**)
(*(*Funzioni di supporto*)*)
(**)
(*validateCoordinate[coord_Integer,occupied_List]:=0<=coord<=99&&!MemberQ[occupied,coord];*)
(**)
(**)
(*placeShip[start_,direction_,size_,occupied_]:=Module[{coords},coords=Switch[direction,"H",Range[start,start+size-1],"V",Table[start+10*i,{i,0,size-1}],_,{}];*)
(*(*Verifica che tutte le coordinate siano valide (0-99) e che non siano gi\[AGrave] occupate*)If[AllTrue[coords,0<=#<=99&]&&AllTrue[coords,FreeQ[occupied,#]&]&&(*Verifica che in orizzontale la nave non superi il bordo*)(direction!="H"||Quotient[start,10]==Quotient[start+size-1,10]),coords,$Failed]];*)
(**)
(**)
(*generateGrid[ships_List]:=Module[{grid=ConstantArray["-",{10,10}]},Do[Do[Module[{row,col},{row,col}={Quotient[coord,10]+1,Mod[coord,10]+1};*)
(*grid[[row,col]]="X";],{coord,ship}],{ship,ships}];*)
(*grid];*)
(**)
(**)
(*BoardDisplay[board_]:=Grid[Join[{Join[{" "},Range[0,9]]},Table[Join[{i-1},Table[If[board[[i,j]]===1,Style["X",Red,Bold]," "],{j,10}]],{i,10}]],Frame->All,Spacings->{1,1}];*)
(**)
(**)
(*convertInput[s_String,base_String]:=Module[{b,result},b=Switch[base,"binario",2,"ottale",8,"esadecimale",16,_,10];*)
(*result=Check[FromDigits[s,b],$Failed];*)
(*If[result===$Failed||!IntegerQ[result]||result<0||result>99,$Failed,result]];*)
(**)
(*(*Funzione per creare un notebook tutorial sulla conversione di base*)*)
(**)
(*createTutorialNotebook[]:=Module[{nb},nb=CreateDocument[{Cell["Conversione da una Base a decimale","Title"],Cell["Questo notebook spiega come convertire numeri da una base qualsiasi al sistema decimale. "<>"Utilizzeremo la funzione FromDigits per effettuare la conversione. "<>"Di seguito vengono riportati alcuni esempi pratici.","Text"],(*Esempio 1:Conversione di un numero binario*)Cell["Esempio 1 - Conversione da Base 2 (binario) a Decimale:","Section"],Cell["Convertiamo il numero \"1011\" dalla base 2 al decimale.","Text"],Cell[BoxData[ToBoxes[FromDigits["1011",2]]],"Input"],Cell["Risultato: 11","Output"],(*Esempio 2:Conversione di un numero esadecimale*)Cell["Esempio 2 - Conversione da Base 16 (esadecimale) a Decimale:","Section"],Cell["Convertiamo il numero \"A3\" dalla base 16 al decimale.","Text"],Cell[BoxData[ToBoxes[FromDigits["A3",16]]],"Input"],Cell["Risultato: 163","Output"],(*Esempio 3:Conversione di un numero in base ottale*)Cell["Esempio 3 - Conversione da Base 8 (ottale) a Decimale:","Section"],Cell["Convertiamo il numero \"157\" dalla base 8 al decimale.","Text"],Cell[BoxData[ToBoxes[FromDigits["157",8]]],"Input"],Cell["Risultato: 111","Output"],(*Sezione di spiegazione teorica*)Cell["Teoria della conversione di base","Section"],Cell["Per convertire un numero da una base qualsiasi a base 10 (decimale), "<>"si moltiplica ogni cifra per la potenza della base corrispondente alla "<>"sua posizione, partendo da destra con esponente 0.","Text"],Cell["Per esempio, per convertire 1011 (base 2) in base 10:","Text"],Cell["1\[Times]2^3 + 0\[Times]2^2 + 1\[Times]2^1 + 1\[Times]2^0 = 8 + 0 + 2 + 1 = 11","Text"],(*Parte teorica aggiuntiva*)Cell["Basi comuni","Subsection"],Cell["Le basi pi\[UGrave] utilizzate in informatica sono:","Text"],Cell[BoxData[ToBoxes[Grid[{{"Base","Nome","Cifre utilizzate"},{"2","Binario","0, 1"},{"8","Ottale","0, 1, 2, 3, 4, 5, 6, 7"},{"10","Decimale","0, 1, 2, 3, 4, 5, 6, 7, 8, 9"},{"16","Esadecimale","0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F"}},Frame->All,Alignment->Left]]],"Output"],(*Parte interattiva per provare le conversioni*)Cell["Prova tu stesso","Section"],Cell["Inserisci un numero e la sua base per convertirlo in decimale:","Text"],Cell[BoxData[ToBoxes[DynamicModule[{input="",base=2,result=""},Column[{Row[{"Numero: ",InputField[Dynamic[input],String,ImageSize->{150,30}],Spacer[20],"Base: ",PopupMenu[Dynamic[base],{2->"Binario (2)",8->"Ottale (8)",16->"Esadecimale (16)"}]}],Button["Converti",result=ToString@Check[FromDigits[input,base],"Input non valido"],Method->"Queued"],Dynamic[If[result=!="",Row[{"Risultato in base 10: ",result}],""]]}]]]],"Input"],(*Link al gioco della battaglia navale*)Cell["Applica le tue conoscenze","Section"],Cell["Ora che hai capito come funziona la conversione di base, "<>"puoi mettere alla prova le tue conoscenze con il gioco della Battaglia Navale "<>"che utilizza le coordinate espresse in diverse basi numeriche.","Text"],Cell[BoxData[ToBoxes[Button["Apri Gioco Battaglia Navale",generateNotebook[],Method->"Queued",ImageSize->{200,40}]]],"Input"]},WindowTitle->"Tutorial Conversione di Base"];*)
(*SetOptions[nb,WindowMargins->{{Automatic,Automatic},{Automatic,10}}];*)
(*nb];*)
(**)
(*(*Interfaccia interattiva principale*)*)
(**)
(*generateNotebook[]:=Module[{interfacciaInterattiva},interfacciaInterattiva=DynamicModule[{seed="",base="",stages={1}},Column[{Dynamic@Column[Map[Function[stage,Switch[stage,1,Panel[Column[{Style["Inserisci il Seed:","Section"],InputField[Dynamic[seed],String,FieldSize->{20,1}],Spacer[10],Button["Avanti",If[StringLength[seed]>0,If[!MemberQ[stages,2],AppendTo[stages,2]],MessageDialog["Inserisci un seed valido!"]],Method->"Queued"]},FrameMargins->20]],2,Panel[Column[{Style["Scegli la base:","Section"],Row[{Button["Binario",(base="binario";*)
(*MessageDialog["Base binaria selezionata!"];*)
(*If[!MemberQ[stages,3],AppendTo[stages,3]]),Method->"Queued",ImageSize->{100,Automatic}],Spacer[20],Button["Ottale",(base="ottale";*)
(*MessageDialog["Base ottale selezionata!"];*)
(*If[!MemberQ[stages,3],AppendTo[stages,3]]),Method->"Queued",ImageSize->{100,Automatic}],Spacer[20],Button["Esadecimale",(base="esadecimale";*)
(*MessageDialog["Base esadecimale selezionata!"];*)
(*If[!MemberQ[stages,3],AppendTo[stages,3]]),Method->"Queued",ImageSize->{120,Automatic}]}]},FrameMargins->20]],3,Panel@DynamicModule[{shipSizes={5,4,3,2},currentShip=1,board=ConstantArray[0,{10,10}],inputStart="",inputEnd="",message="",occupiedCells={}},Column[{Style["Base: "<>base,"Section"],Button["Apri Tutorial sulla Conversione di Base",createTutorialNotebook[],Method->"Queued"],Spacer[10],Dynamic@BoardDisplay[board],Dynamic[If[currentShip<=Length[shipSizes],Column[{Style["Nave di dimensione "<>ToString[shipSizes[[currentShip]]]<>":","Subsection"],Row[{Style["Inizio: ",Bold],InputField[Dynamic[inputStart],String,FieldSize->10],Spacer[10],Style["Fine: ",Bold],InputField[Dynamic[inputEnd],String,FieldSize->10]}],Button["Verifica",Module[{n1,n2,start,end,orientation,shipCoordinates,size,i},size=shipSizes[[currentShip]];*)
(*n1=convertInput[inputStart,base];*)
(*n2=convertInput[inputEnd,base];*)
(*If[n1===$Failed||n2===$Failed,message="Input non valido! Inserisci un numero nella base "<>base<>" tra 0 e 99.",(*Verifico se le coordinate sono per una nave orizzontale o verticale*)If[Quotient[n1,10]==Quotient[n2,10]&&Abs[n1-n2]==size-1,(*Nave orizzontale*)orientation="H";*)
(*{start,end}=Sort[{n1,n2}];*)
(*shipCoordinates=placeShip[start,orientation,size,occupiedCells],If[Mod[n1,10]==Mod[n2,10]&&Abs[n1-n2]==(size-1)*10,(*Nave verticale*)orientation="V";*)
(*{start,end}=Sort[{n1,n2}];*)
(*shipCoordinates=placeShip[start,orientation,size,occupiedCells],(*Coordinate non valide*)message="Le coordinate non corrispondono a una nave di dimensione "<>ToString[size]<>"!";*)
(*Return[]]]];*)
(*If[shipCoordinates===$Failed,message="Posizione non valida o nave sovrapposta!",(*Aggiorno la board e le celle occupate*)For[i=1,i<=Length[shipCoordinates],i++,AppendTo[occupiedCells,shipCoordinates[[i]]];*)
(*board[[Quotient[shipCoordinates[[i]],10]+1,Mod[shipCoordinates[[i]],10]+1]]=1;];*)
(*message="Nave posizionata correttamente!";*)
(*currentShip++;*)
(*inputStart="";*)
(*inputEnd="";]],Method->"Queued"],Spacer[5],Dynamic[Style[message,If[StringMatchQ[message,"Nave posizionata*"],Green,Red]]]}],Style["Tutte le navi posizionate! Complimenti!",Bold,Green]]]}]]]],stages]]}]];*)
(*CreateDocument[{Cell["Battaglia Navale con Conversione di Base","Title"],Cell["Questo gioco ti aiuta a esercitarti nella conversione di basi numeriche. "<>"Inserisci un seed e scegli una base per iniziare. "<>"Poi posiziona le navi indicando le coordinate di inizio e fine in quella base numerica.","Text"],Cell[BoxData[ToBoxes[Button["Apri Tutorial sulla Conversione di Base",createTutorialNotebook[],Method->"Queued",ImageSize->{250,40}]]],"Input"],Cell[BoxData[ToBoxes[interfacciaInterattiva]],"Input"]},WindowTitle->"Battaglia Navale"]];*)
(**)
(*End[];*)
(*EndPackage[];*)
